Repository Azure/CanadaPubSecALZ, pull requests merged in 2021-11, with the labels that each got.

#51 Onboarding guide tweaking
  docs/onboarding/ado.md
Labels: documentation

#59 Telemetry - enable Azure customer usage attribution
  README.md
  azresources/telemetry/customer-usage-attribution-management-group.bicep
  azresources/telemetry/customer-usage-attribution-resource-group.bicep
  azresources/telemetry/customer-usage-attribution-subscription.bicep
  azresources/telemetry/customer-usage-attribution-tenant.bicep
  config/telemetry.json
  docs/onboarding/ado.md
  landingzones/lz-generic-subscription/main.bicep
  landingzones/lz-healthcare/main.bicep
  landingzones/lz-machinelearning/main.bicep
  landingzones/lz-platform-connectivity-hub-azfw/main-azfw-policy.bicep
  landingzones/lz-platform-connectivity-hub-azfw/main.bicep
  landingzones/lz-platform-connectivity-hub-nva/main.bicep
  landingzones/lz-platform-logging/main.bicep
  management-groups/structure.bicep
  policy/builtin/assignments/asb.bicep
  policy/builtin/assignments/cis-msft-130.bicep
  policy/builtin/assignments/fedramp-moderate.bicep
  policy/builtin/assignments/hitrust-hipaa.bicep
  policy/builtin/assignments/location.bicep
  policy/builtin/assignments/nist80053r4.bicep
  policy/builtin/assignments/nist80053r5.bicep
  policy/builtin/assignments/pbmm.bicep
  policy/custom/assignments/aks.bicep
  policy/custom/assignments/asc.bicep
  policy/custom/assignments/ddos.bicep
  policy/custom/assignments/dns-private-endpoints.bicep
  policy/custom/assignments/loganalytics.bicep
  policy/custom/assignments/network.bicep
  policy/custom/assignments/tags.bicep
  roles/la-vminsights-readonly.bicep
  roles/lz-appowner.bicep
  roles/lz-subowner.bicep
Labels: documentation, enhancement

#61 Improve archetype parameter JSON schemas
  .github/workflows/pull-request-check.yml
  .pipelines/pull-request-check.yml
  .pipelines/templates/steps/config-subscription.yml
  docs/archetypes/generic-subscription.md
  docs/archetypes/healthcare.md
  docs/archetypes/logging.md
  docs/archetypes/machinelearning.md
  schemas/latest/landingzones/lz-generic-subscription.json
  schemas/latest/landingzones/lz-healthcare.json
  schemas/latest/landingzones/lz-machinelearning.json
  schemas/latest/landingzones/types/aks.json
  schemas/latest/landingzones/types/aml.json
  schemas/latest/landingzones/types/automation.json
  schemas/latest/landingzones/types/hubNetwork.json
  schemas/latest/landingzones/types/keyVault.json
  schemas/latest/landingzones/types/resourceTags.json
  schemas/latest/landingzones/types/securityCenter.json
  schemas/latest/landingzones/types/serviceHealthAlerts.json
  schemas/latest/landingzones/types/sqldb.json
  schemas/latest/landingzones/types/sqlmi.json
  schemas/latest/landingzones/types/subscriptionBudget.json
  schemas/latest/landingzones/types/subscriptionRoleAssignments.json
  schemas/latest/landingzones/types/subscriptionTags.json
  schemas/latest/landingzones/types/synapse.json
  schemas/latest/readme.md
  tests/schemas/notes.txt
Labels: enhancement

#63 AuditEvent log category for Automation Account's Diagnostic Settings
  policy/custom/definitions/policy/LA-Microsoft.Automation-automationAccounts/azurepolicy.rules.json
Labels: regulatory compliance

#76 Platform Management Group alignment with Reference Architecture
  config/variables/CanadaESLZ-main.yml
  config/variables/devopsincanada-main.yml
  docs/archetypes/logging.md
  docs/architecture.md
  docs/media/architecture/management-group-structure.jpg
  docs/onboarding/ado.md
  management-groups/structure.bicep
Labels: enhancement

#92 Ensure PRs does not trigger pipeline runs
  .pipelines/management-groups.yml
  .pipelines/platform-connectivity-hub-azfw-policy.yml
  .pipelines/platform-connectivity-hub-azfw.yml
  .pipelines/platform-connectivity-hub-nva.yml
  .pipelines/platform-logging.yml
  .pipelines/policy.yml
  .pipelines/roles.yml
  .pipelines/subscriptions.yml
Labels: bug

#91 Support Audit, Deny & Disabled effects for Tag policy
  policy/custom/definitions/policyset/Tags.bicep
  policy/custom/definitions/policyset/Tags.parameters.json
  policy/custom/definitions/policyset/templates/Tags-Require-Tag-ResourceGroup/azurepolicy.json
Labels: enhancement

#99 Update Hub Connectivity ADO Pipelines
  .pipelines/templates/steps/deploy-platform-connectivity-hub-azfw.yml
  .pipelines/templates/steps/deploy-platform-connectivity-hub-nva.yml
Labels: bug

#96 AKS - Azure CNI and Calico Network Policy (#48)
  azresources/containers/aks/aks-with-cmk.bicep
  azresources/containers/aks/aks-without-cmk.bicep
  azresources/containers/aks/main.bicep
  config/subscriptions/CanadaESLZ-main/pubsec/LandingZones/DevTest/8c6e48a4-4c73-4a1f-9f95-9447804f2c98_machinelearning_canadacentral.json
  config/subscriptions/CanadaESLZ-main/pubsec/LandingZones/DevTest/ec6c5689-db04-4f1e-b76d-834a51dd0e27_machinelearning_canadacentral.json
  config/subscriptions/CanadaESLZ-main/pubsec/LandingZones/DevTest/f08c3057-1713-4a6f-b7e6-0df355b60c30_machinelearning_canadacentral.json
  config/subscriptions/CanadaESLZ-main/pubsec/LandingZones/DevTest/f459218a-e8bb-49c9-b768-ee6828a144aa_machinelearning_canadacentral.json
  docs/archetypes/machinelearning.md
  landingzones/lz-machinelearning/lz.bicep
  schemas/latest/landingzones/types/aks.json
  schemas/latest/readme.md
  tests/schemas/lz-machinelearning/AKS-AzureCNI-AzureNP.json
  tests/schemas/lz-machinelearning/AKS-AzureCNI-Calico.json
  tests/schemas/lz-machinelearning/AKS-Kubenet-Calico.json
  tests/schemas/lz-machinelearning/BudgetIsFalse.json
  tests/schemas/lz-machinelearning/BudgetIsTrue.json
  tests/schemas/lz-machinelearning/EmptyResourceTags.json
  tests/schemas/lz-machinelearning/EmptySubscriptionTags.json
  tests/schemas/lz-machinelearning/FullDeployment-With-Hub.json
  tests/schemas/lz-machinelearning/FullDeployment-Without-Hub.json
  tests/schemas/lz-machinelearning/SQLDB-aadAuthOnly.json
  tests/schemas/lz-machinelearning/SQLDB-mixedAuth.json
  tests/schemas/lz-machinelearning/SQLDB-sqlAuth.json
  tests/schemas/lz-machinelearning/SQLDBIsFalse.json
  tests/schemas/lz-machinelearning/SQLMIIsFalse.json
  tests/schemas/lz-machinelearning/WithoutCMK.json
Labels: enhancement
