Repository Azure/CanadaPubSecALZ, pull requests merged in 2022-04, with the labels that each got.

#229 Updating recommendations to reflect licensing reqs
  README.md
  docs/gc-30-day-cloud-guardrails.md
Labels: documentation

#250 Migrate Networking configuration to JSON parameters file
  .github/workflows/consistency-check.yml
  .github/workflows/pull-request-check.yml
  .pipelines/platform-connectivity-hub-azfw-policy.yml
  .pipelines/platform-connectivity-hub-azfw.yml
  .pipelines/platform-connectivity-hub-nva.yml
  .pipelines/templates/steps/deploy-platform-connectivity-hub-azfw-policy.yml
  .pipelines/templates/steps/deploy-platform-connectivity-hub-azfw.yml
  .pipelines/templates/steps/deploy-platform-connectivity-hub-nva.yml
  config/networking/CanadaESLZ-main/hub-azfw-policy/azure-firewall-policy.parameters.json
  config/networking/CanadaESLZ-main/hub-azfw/hub-network.parameters.json
  config/networking/CanadaESLZ-main/hub-nva/hub-network.parameters.json
  config/networking/devopsincanada-main/hub-azfw-policy/azure-firewall-policy.parameters.json
  config/networking/devopsincanada-main/hub-azfw/hub-network.parameters.json
  config/networking/devopsincanada-main/hub-nva/hub-network.parameters.json
  config/variables/CanadaESLZ-main.yml
  config/variables/common.yml
  config/variables/devopsincanada-main.yml
  docs/archetypes/hubnetwork-azfw.md
  docs/archetypes/hubnetwork-nva-fortigate.md
  docs/onboarding/azure-devops-pipelines.md
  schemas/latest/landingzones/lz-platform-connectivity-hub-azfw-policy.json
  schemas/latest/landingzones/lz-platform-connectivity-hub-azfw.json
  schemas/latest/landingzones/lz-platform-connectivity-hub-nva.json
  schemas/latest/readme.md
  tests/schemas/lz-platform-connectivity-hub-azfw-policy/FullDeployment.json
  tests/schemas/lz-platform-connectivity-hub-azfw/BudgetIsFalse.json
  tests/schemas/lz-platform-connectivity-hub-azfw/FullDeployment-WithAzureFirewallPolicy.json
  tests/schemas/lz-platform-connectivity-hub-azfw/FullDeployment-WithLogAnalyticsWorkspace.json
  tests/schemas/lz-platform-connectivity-hub-azfw/FullDeployment.json
  tests/schemas/lz-platform-connectivity-hub-nva/BudgetIsFalse.json
  tests/schemas/lz-platform-connectivity-hub-nva/FullDeployment-WithLogAnalyticsWorkspace.json
  tests/schemas/lz-platform-connectivity-hub-nva/FullDeployment.json
  tests/schemas/run-tests.sh
Labels: breaking change

#254 Revise subnet configuration for Machine Learning archetype
  config/subscriptions/CanadaESLZ-main/pubsec/LandingZones/DevTest/8c6e48a4-4c73-4a1f-9f95-9447804f2c98_machinelearning_canadacentral.json
  config/subscriptions/CanadaESLZ-main/pubsec/LandingZones/DevTest/ec6c5689-db04-4f1e-b76d-834a51dd0e27_machinelearning_canadacentral.json
  config/subscriptions/CanadaESLZ-main/pubsec/LandingZones/DevTest/f08c3057-1713-4a6f-b7e6-0df355b60c30_machinelearning_canadacentral.json
  config/subscriptions/CanadaESLZ-main/pubsec/LandingZones/DevTest/f459218a-e8bb-49c9-b768-ee6828a144aa_machinelearning_canadacentral.json
  docs/archetypes/machinelearning.md
  landingzones/lz-machinelearning/lz.bicep
  landingzones/lz-machinelearning/main.bicep
  landingzones/lz-machinelearning/networking.bicep
  schemas/latest/landingzones/lz-machinelearning.json
  schemas/latest/readme.md
  tests/landingzones/lz-machinelearning/deployment-tests/test-runner.bicep
  tests/schemas/lz-machinelearning/AKS-AzureCNI-AzureNP.json
  tests/schemas/lz-machinelearning/AKS-AzureCNI-Calico.json
  tests/schemas/lz-machinelearning/AKS-Kubenet-Calico.json
  tests/schemas/lz-machinelearning/AKSIsFalse.json
  tests/schemas/lz-machinelearning/AppServiceLinuxContainerIsFalse.json
  tests/schemas/lz-machinelearning/AppServiceLinuxContainerPrivateEndpointIsFalse.json
  tests/schemas/lz-machinelearning/BudgetIsFalse.json
  tests/schemas/lz-machinelearning/BudgetIsTrue.json
  tests/schemas/lz-machinelearning/EmptyResourceTags.json
  tests/schemas/lz-machinelearning/EmptySubscriptionTags.json
  tests/schemas/lz-machinelearning/FullDeployment-With-Hub.json
  tests/schemas/lz-machinelearning/FullDeployment-With-Location.json
  tests/schemas/lz-machinelearning/FullDeployment-Without-Hub.json
  tests/schemas/lz-machinelearning/SQLDB-aadAuthOnly.json
  tests/schemas/lz-machinelearning/SQLDB-mixedAuth.json
  tests/schemas/lz-machinelearning/SQLDB-sqlAuth.json
  tests/schemas/lz-machinelearning/SQLDBIsFalse.json
  tests/schemas/lz-machinelearning/SQLMIIsFalse.json
  tests/schemas/lz-machinelearning/WithoutCMK.json
Labels: breaking change

#256 Revise subnet configuration for Healthcare archetype
  config/subscriptions/CanadaESLZ-main/pubsec/LandingZones/DevTest/82f7705e-3386-427b-95b7-cbed91ab29a7_healthcare_canadacentral.json
  docs/archetypes/healthcare.md
  landingzones/lz-healthcare/lz.bicep
  landingzones/lz-healthcare/main.bicep
  landingzones/lz-healthcare/networking.bicep
  schemas/latest/landingzones/lz-healthcare.json
  schemas/latest/readme.md
  tests/landingzones/lz-healthcare/deployment-tests/test-runner.bicep
  tests/schemas/lz-healthcare/BudgetIsFalse.json
  tests/schemas/lz-healthcare/BudgetIsTrue.json
  tests/schemas/lz-healthcare/EmptyResourceTags.json
  tests/schemas/lz-healthcare/EmptySubscriptionTags.json
  tests/schemas/lz-healthcare/FullDeployment-With-Hub.json
  tests/schemas/lz-healthcare/FullDeployment-With-Location.json
  tests/schemas/lz-healthcare/FullDeployment-Without-Hub.json
  tests/schemas/lz-healthcare/SQLDB-aadAuthOnly.json
  tests/schemas/lz-healthcare/SQLDB-mixedAuth.json
  tests/schemas/lz-healthcare/SQLDB-sqlAuth.json
  tests/schemas/lz-healthcare/SQLDBIsFalse.json
  tests/schemas/lz-healthcare/Synapse-aadAuthOnly.json
  tests/schemas/lz-healthcare/Synapse-mixedAuth.json
  tests/schemas/lz-healthcare/Synapse-sqlAuth.json
  tests/schemas/lz-healthcare/WithoutCMK.json
Labels: breaking change

#268 Snapshot ARM parameters JSON schemas
  schemas/v0.5.0/landingzones/lz-generic-subscription.json
  schemas/v0.5.0/landingzones/lz-healthcare.json
  schemas/v0.5.0/landingzones/lz-machinelearning.json
  schemas/v0.5.0/landingzones/lz-platform-connectivity-hub-azfw-policy.json
  schemas/v0.5.0/landingzones/lz-platform-connectivity-hub-azfw.json
  schemas/v0.5.0/landingzones/lz-platform-connectivity-hub-nva.json
  schemas/v0.5.0/landingzones/lz-platform-logging.json
  schemas/v0.5.0/landingzones/types/aks.json
  schemas/v0.5.0/landingzones/types/aml.json
  schemas/v0.5.0/landingzones/types/appServiceLinuxContainer.json
  schemas/v0.5.0/landingzones/types/automation.json
  schemas/v0.5.0/landingzones/types/backupRecoveryVault.json
  schemas/v0.5.0/landingzones/types/hubNetwork.json
  schemas/v0.5.0/landingzones/types/keyVault.json
  schemas/v0.5.0/landingzones/types/location.json
  schemas/v0.5.0/landingzones/types/logAnalyticsWorkspaceId.json
  schemas/v0.5.0/landingzones/types/resourceTags.json
  schemas/v0.5.0/landingzones/types/securityCenter.json
  schemas/v0.5.0/landingzones/types/serviceHealthAlerts.json
  schemas/v0.5.0/landingzones/types/sqldb.json
  schemas/v0.5.0/landingzones/types/sqlmi.json
  schemas/v0.5.0/landingzones/types/subscriptionBudget.json
  schemas/v0.5.0/landingzones/types/subscriptionRoleAssignments.json
  schemas/v0.5.0/landingzones/types/subscriptionTags.json
  schemas/v0.5.0/landingzones/types/synapse.json
  schemas/v0.5.0/readme.md
Labels: documentation

#271 PowerShell deployment scripts
  config/variables/CanadaESLZ-main.yml
  scripts/deployments/E2E.ps1
  scripts/deployments/Functions/EnvironmentContext.ps1
  scripts/deployments/Functions/HubNetworkWithAzureFirewall.ps1
  scripts/deployments/Functions/HubNetworkWithNVA.ps1
  scripts/deployments/Functions/Logging.ps1
  scripts/deployments/Functions/ManagementGroups.ps1
  scripts/deployments/Functions/Policy.ps1
  scripts/deployments/Functions/Roles.ps1
  scripts/deployments/Functions/Subscriptions.ps1
  scripts/deployments/Install-Prerequisites.ps1
Labels: enhancement
