Repository Azure/CanadaPubSecALZ, pull requests merged in 2022-03, with the labels that each got.

#201 Revise subscription deployment instructions
  config/subscriptions/README.md
  docs/archetypes/authoring-guide.md
Labels: documentation

#207 Fix pipeline scripts reference to `subscription-ci`
  docs/onboarding/azure-devops-scripts.md
  scripts/onboarding/create-pipelines.bat
  scripts/onboarding/delete-pipelines.bat
  scripts/onboarding/run-pipelines.bat
Labels: bug

#216 Document delete lock usage
  docs/archetypes/generic-subscription.md
  docs/archetypes/healthcare.md
  docs/archetypes/hubnetwork-azfw.md
  docs/archetypes/hubnetwork-nva-fortigate.md
  docs/archetypes/logging.md
  docs/archetypes/machinelearning.md
Labels: documentation

#215 ADO Pipeline onboarding - add instructions for customizing policy set assignments in
  docs/onboarding/azure-devops-pipelines.md
Labels: documentation

#218 Formatting changes to policy section
  docs/onboarding/azure-devops-pipelines.md
Labels: documentation

#224 Improve `delete-management-groups.bat` script
  .pipelines/management-groups.yml
  docs/media/onboarding/management-groups-01.png
  docs/media/onboarding/management-groups-02.png
  docs/media/onboarding/management-groups-03.png
  docs/media/onboarding/management-groups-04.png
  docs/media/onboarding/run-1-1.png
  docs/media/onboarding/run-1-2.png
  docs/media/onboarding/run-1-3.png
  docs/media/onboarding/run-2-1.png
  docs/media/onboarding/run-2-2.png
  docs/media/onboarding/run-2-3.png
  docs/media/onboarding/run-2-4.png
  docs/media/onboarding/run-3-1.png
  docs/media/onboarding/run-3-2.png
  docs/media/onboarding/run-3-3.png
  docs/onboarding/azure-devops-scripts.md
  scripts/onboarding/delete-management-groups.bat
Labels: documentation, scripts

#226 Initial GC 30-day cloud guardrails compliance/guidance
  docs/gc-30-day-cloud-guardrails.md
Labels: documentation
