Repository Azure/CanadaPubSecALZ, pull requests merged in 2022-05, with the labels that each got.

#285 Correct wiring of the subscriptions-ci pipeline and prompt for NVA firewall username & password
  .pipelines/README.md
  docs/archetypes/authoring-guide.md
  docs/architecture.md
  docs/onboarding/azure-devops-pipelines.md
  docs/onboarding/azure-devops-scripts.md
  scripts/onboarding/create-pipelines.bat
  scripts/onboarding/create-variable-group.bat
  scripts/onboarding/set-variables.DevOpsOrgName.bat
  scripts/onboarding/set-variables.ocag148outlook.bat
Labels: bug, enhancement, scripts

#286 Support jobs in GitHub Actions
  .github/workflows/0-everything.yml
  .github/workflows/1-management-groups.yml
  .github/workflows/2-roles.yml
  .github/workflows/3-logging.yml
  .github/workflows/4-policy.yml
  .github/workflows/5-hub-network-with-azure-firewall.yml
  .github/workflows/5-hub-network-with-nva.yml
  .github/workflows/6-subscriptions.yml
  scripts/deployments/RunWorkflows.ps1
Labels: enhancement

#295 Disable metrics in diagnostic settings for AKS through Policy
  policy/custom/definitions/policyset/LogAnalytics.bicep
Labels: bug

#299 Concurrent role deployment with PowerShell & GitHub Actions
  .github/workflows/0-everything.yml
  .github/workflows/2-roles.yml
  roles/la-vminsights-readonly.bicep
  roles/lz-appowner.bicep
  roles/lz-netops.bicep
  roles/lz-secops.bicep
  roles/lz-subowner.bicep
  scripts/deployments/Functions/Roles.ps1
  scripts/deployments/RunWorkflows.ps1
Labels: enhancement

#297 GitHub Actions: disable fail fast for matrix deployments
  .github/workflows/0-everything.yml
  .github/workflows/4-policy.yml
  .github/workflows/6-subscriptions.yml
Labels: bug

#300 Flexible policy deployment using PowerShell & GitHub Actions
  .github/workflows/0-everything.yml
  .github/workflows/4-policy.yml
  scripts/deployments/Functions/Policy.ps1
  scripts/deployments/RunWorkflows.ps1
Labels: enhancement

#303 Log Analytics solutions for SQL servers on machines
  azresources/monitor/log-analytics.bicep
  docs/archetypes/logging.md
  docs/gc-30-day-cloud-guardrails.md
  landingzones/lz-platform-logging/main.bicep
Labels: documentation, enhancement

#310 Documentation for Service Health
  docs/archetypes/generic-subscription.md
  docs/archetypes/healthcare.md
  docs/archetypes/hubnetwork-azfw.md
  docs/archetypes/hubnetwork-nva-fortigate.md
  docs/archetypes/logging.md
  docs/archetypes/machinelearning.md
Labels: documentation
